Added http proxy options to configuration
savoirfairelinux/ansible-nexus3-oss pull request #19
Opened 2017-09-06 12:10 UTC by balux

added http and https proxy settings.

Tried to add options for _nonProxyHosts_ settings, but I didn't get it to work. Maybe there is sombody who can help?

```java
  /**
   * Set hosts that should not be proxied. Accepts Java "http.nonProxyHosts" wildcard patterns (one per line, no '|'
   * hostname delimiters).
   * Previously configured values can be removed by calling this with no parameters.
   */
  void nonProxyHosts(String... nonProxyHosts);
```
From:
https://github.com/sonatype/nexus-public/blob/tag-3.3.1-01/components/nexus-core/src/main/java/org/sonatype/nexus/CoreApi.java

2017-09-06 19:54 UTC, dannyk81 commented
I was able to get `nonProxyHosts` to work, however I think there's something wrong with.

based on the API doc, I assume that `core.nonProxyHosts` should be called for each item, however they just overwrite each other and I end up with just the last entry - is that what you've experienced?

I added this to end of your groovy script:
```
if (parsed_args.with_http_proxy) {
    core.nonProxyHosts()
    parsed_args.non_proxy_hosts.each { core.nonProxyHosts(it) }
}
```

defaults:
```
nexus_non_proxy_hosts:
  - "localhost"
  - "127.*"
  - "[::1]"
```

tasks:
```
      non_proxy_hosts: "{{ nexus_non_proxy_hosts }}"
```

2017-09-06 20:05 UTC, samherve commented
There seem to be a trick with groovy calling java varargs : have you tried with something like `core.nonProxyHosts(parsed_args.proxy_exclude_hosts as String[])` ?

2017-09-06 20:06 UTC, samherve requested changes

2017-09-06 20:06 UTC, samherve commented on tasks/main.yml
> +      https_proxy_host: "{{ nexus_http_proxy_host }}"
There seem to be a typo here ? (missing "s"). Same on next line.

2017-09-06 20:56 UTC, dannyk81 commented
@samherve That did it!

with `core.nonProxyHosts(parsed_args.proxy_exclude_hosts as String[])` it works perfectly!

2017-09-07 16:59 UTC, balux commented
thanks!

fixed typo and added new option nexus_proxy_exclude_hosts

2017-10-03 15:40 UTC, merged