Backup/Restore, blob separation, purge function
savoirfairelinux/ansible-nexus3-oss pull request #9
Opened 2017-02-23 15:37 UTC by Chrislevi

- Backup and Restore procedures added. 3.2.1 newest feature
- Single blob for each supported format. 
- Added purge ability
- Minor indention fix

2017-02-23 15:38 UTC, Chrislevi commented
@hagzag

2017-02-28 12:43 UTC, Chrislevi commented
@hagzag @samherve Bump.

2017-03-04 22:19 UTC, hagzag commented
@samherve could you take a look @ this PR this is one of my colleagues which added backup & restore capabilities

2017-03-06 13:28 UTC, samherve requested changes

2017-03-06 13:28 UTC, samherve commented on defaults/main.yml
> +    write_policy: allow
Why not keeping allow_once on maven releases ?

2017-03-06 13:28 UTC, samherve commented on defaults/main.yml
> +  blob_store: "{{ nexus_blob_prefix }}mvn"
I think that there may be an issue about a kind of "backward compatibility" here : if someone has already provisionned a nexus instance using the (previous) default role vars, then this update of the role becomes incompatible with his current nexus installation ?

2017-03-06 13:28 UTC, samherve commented on tasks/nexus_install.yml
> +    owner: "{{ nexus_os_user }}"
Why should the nexus executable be allowed to overwrite itself ? I considered this a security point to have the program (as opposed to data) filed owned by root

2017-03-09 14:39 UTC, Chrislevi commented on defaults/main.yml
> +    write_policy: allow
I'll revert it to allow_once.

2017-03-09 15:27 UTC, Chrislevi commented on defaults/main.yml
> +  blob_store: "{{ nexus_blob_prefix }}mvn"
I'm working on a 'splited' and default flows to the blobstore configuration

2017-03-09 15:29 UTC, Chrislevi commented on tasks/nexus_install.yml
> +    owner: "{{ nexus_os_user }}"
Rolling back, had problems deploying scripts to the script dir located in nexus_install dir. never mind, i've found a simple solution.

2017-03-09 17:02 UTC, Chrislevi commented
@samherve  Please re-overview the pr, i've pushed the requested changes :)

2017-04-12 15:39 UTC, Chrislevi commented
bump

2017-04-25 19:35 UTC, samherve commented on tasks/nexus_install.yml
> +  when: nexus_version >= '3.2.1-01'
I think this line should stay as it was `nexus_version >= '3.1.0'` ? there was a change in the config paths at version 3.1.0, so there is no need to bump this version (see line 66 above).

2017-04-25 19:37 UTC, samherve requested changes
Hi, I finally found time to test this review, apart from y single comment about keeping `when: nexus_version >= '3.1.0'` , everything works fine to me. 

I also tested it succesfully with the latest 3.3.0-01 nexus release.

2017-04-26 19:47 UTC, merged